version: '3'

services:
  app:
    build:
      context: .
    image: starwars/web:latest
    command: bundle exec foreman start -f Procfile.dev
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env.development
      - .env.development.local
    environment:
      - ACTION_MAILER_HOST=mailhog

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 1025:1025
      - 8025:8025
